apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "libero-editor.fullname" . }}-client
  labels:
    app.kubernetes.io/name: {{ include "libero-editor.name" . }}
    helm.sh/chart: {{ include "libero-editor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "libero-editor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libero-editor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: client
    spec:
      containers:
        - name: {{ .Chart.Name }}-client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          nodeSelector:
            kubernetes.io/arch: amd64
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
