apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "libero-editor.fullname" . }}-pdf-service
  labels:
    app.kubernetes.io/name: {{ include "libero-editor.name" . }}
    helm.sh/chart: {{ include "libero-editor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: pdf-service
spec:
  replicas: {{ .Values.pdfService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "libero-editor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: pdf-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libero-editor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: pdf-service
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: {{ .Chart.Name }}-pdf-service
          image: "{{ .Values.pdfService.image.repository }}:{{ .Values.pdfService.image.tag }}"
          imagePullPolicy: {{ .Values.pdfService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pdfService.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ARTICLE_STORE_PATH
              value: 'http://{{ include "libero-editor.fullname" . }}-article-store:8080/articles/'
            - name: EDITOR_URL
              value: 'https://{{ .Values.ingress.host }}'
            - name: GENERATION_START_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pdfService.secret | quote }}
                  key: startUrl
            - name: GENERATION_STATUS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pdfService.secret | quote }}
                  key: statusUrl
            - name: GENERATION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pdfService.secret | quote }}
                  key: apiKey
